accounts/urls.py
from django.conf.urls import url
from accounts.views import ExpenseListChart

urlpatterns = [
    url(r'^$', ExpenseListChart.as_view(), name="chart_view"),
]

mymoney/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from .views import HomeView


urlpatterns = [
    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
from django.db import models


@python_2_unicode_compatible  # only if you need to support Python 2
class MainCategory(models.Model):
    category_name = models.CharField("Category Name", max_length=120, unique=True)

    def __str__(self):
        return self.category_name


@python_2_unicode_compatible  # only if you need to support Python 2
class SubCategory(models.Model):
    main_category = models.ForeignKey(MainCategory, on_delete=models.CASCADE)
    category_name = models.CharField("Category Name", max_length=120, unique=True)

    class Meta:
        ordering = ['main_category__category_name']

    def __str__(self):
        return self.category_name

# test commit
class DebitCategory(models.Model):
    category_name = models.CharField("Category Name", max_length=120, unique=True)

    def __str__(self):
        return self.category_name


class Expenses(models.Model):
    main_category = models.ForeignKey(MainCategory, on_delete=models.CASCADE)
    sub_category = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
    debit_category = models.ForeignKey(DebitCategory, on_delete=models.CASCADE)
    description = models.TextField()
    spent_date = models.DateField("Spent on Date")
    amount = models.FloatField("Amount Spent")
    create_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{0}".format(self.description)


class UploadData(models.Model):
    data = models.FileField()
    upload_time = models.DateTimeField(auto_now_add=True)
    debit_category = models.ForeignKey(DebitCategory, on_delete=models.CASCADE)

accounts/forms.py
from django import forms
import datetime


class DateRangeForm(forms.Form):
    start_date = forms.DateTimeField(initial=datetime.date.today)
    end_date = forms.DateTimeField(initial=datetime.date.today)

    #this is comment

accounts/views.py
from django.shortcuts import render
from django.views.generic import View
from django.views.generic.edit import FormMixin
from .models import Expenses
from django.db.models import F, FloatField, Sum
from .forms import  DateRangeForm


class ExpenseListChart(View):
    http_method_names = ['get', 'post']
    template_name = "expenses.html"
    context_object_name = 'expense_main_category'
    form = DateRangeForm

    def get(self, request, *args, **kwargs):
        print("####################")
        context = self.get_context_data(request)
        return render(request, self.template_name, context)

    def get_context_data(self, request):

        context = {}
        context['expense_main_sub_category'] = Expenses.objects.values('main_category__category_name',
                                                                       'sub_category__category_name') \
            .annotate(check_sum=Sum(F('amount'), output_field=FloatField()))
        context['total_amount'] = Expenses.objects.aggregate(Sum(F('amount'), output_field=FloatField()))

        context['date_range_form'] = DateRangeForm(request.GET)
        context['expense_main_category'] = self.get_queryset(request)

        return context

    def get_queryset(self, request):
        print("in query set")
        form = DateRangeForm(request.POST)
        print (request.POST)
        if form.is_valid():
            start_date = form.cleaned_data['start_date']
            end_date = form.cleaned_data['end_date']
            print (start_date,   end_date)
            expenses = Expenses.objects.filter(spent_date__range=(start_date, end_date))
        else:
            expenses = Expenses.objects
        print (expenses)
        return expenses.values('main_category__category_name').annotate(
            check_sum=Sum(F('amount'), output_field=FloatField()))

    def post(self, request, *args, **kwargs):
        print(" ********************************** ")
        context = self.get_context_data(request)

        return render(request, self.template_name, context)

mymoney/views.py
from django.views.generic import View
from django.shortcuts import redirect


class HomeView(View):

    def get(self, request):
        return redirect('chart_view')

templates/admin_test.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls admin_static %}

{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}"/>
{% endblock %}

{% block content %}

    <form action="{% url 'chart_view' %}" method="post">
        {% csrf_token %}
        {{ date_range_form }}
         <div class="submit-row">
            <input type="submit" value="Submit" class="default"/>
        </div>
    </form>
{% endblock %}

templates/base.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls admin_static %}

{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}"/>
{% endblock %}

{% block breadcrumbs %}
    <div class="breadcrumbs">
        <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
        &rsaquo; <a href="{% url 'admin:app_list' app_label=opts.app_label %}">{{ app_label|capfirst|escape }}</a>
        &rsaquo; {% if has_change_permission %}<a href="{% url opts|admin_urlname:'changelist' %}">
        {{ opts.verbose_name_plural|capfirst }}</a>{% else %}{{ opts.verbose_name_plural|capfirst }}{% endif %}
        &rsaquo; {% trans 'Upload' %}
    </div>
{% endblock %}

{% block content %}
    <form action="{% url opts|admin_urlname:'upload' %}" method="post" id="productkey_upload_form"
          {% if form.is_multipart %}enctype="multipart/form-data"{% endif %}>
        {% csrf_token %}
        <div>
            {% for fieldset in adminform %}
                {% include "admin/includes/fieldset.html" %}
            {% endfor %}
        </div>
        <div class="submit-row">
            <input type="submit" value="Submit" class="default"/>
        </div>
    </form>
{% endblock %}

templates/expenses.html
{% load static %}
{% load bootstrap3 %}
<!DOCTYPE HTML>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<title>Highcharts Example</title>
		<script type="text/javascript" src=" {% static 'js/jquery-1.11.3.min.js' %}"></script>
{% bootstrap_css %}
{% bootstrap_javascript %}
		<!--<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}"/>-->
		<!--<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-grid.min.css' %}"/>-->
		<!--<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-reboot.min.css' %}"/>-->
		<!---->
		<!--<script type="text/javascript" src=" {% static 'js/bootstrap.min.js' %}"></script>-->
		<!--<script type="text/javascript" src=" {% static 'js/bootstrap.bundle.min.js' %}"></script>-->
		<!--{% bootstrap_javascript %}-->
		<style type="text/css">
${demo.css}
		</style>

		<script src="{% static 'js/charts/highcharts.js' %}"></script>
		<script src="{% static 'js/charts/modules/drilldown.js' %}"></script>
	</head>
	<body>

{% bootstrap_messages %}

    <form class="form" action="{% url 'chart_view' %}" method="post">
        {% csrf_token %}
        <div class="form-group has-error">
            <label class="sr-only" for="id_start_date">Start date</label>
            <input name="start_date" title="This field is required." class="form-control" id="id_start_date" required="" type="date" placeholder="Start date">
        </div>

        <div class="form-group has-error">
            <label class="sr-only" for="id_end_date">End date</label>
            <input name="end_date" title="This field is required." class="form-control" id="id_end_date" required="" type="date" placeholder="End date">
        </div>
		{% buttons %}
			<button type="submit" class="btn btn-primary">
			  {% bootstrap_icon "star" %} Submit
			</button>
		  {% endbuttons %}
	</form>




<div id="container" style="min-width: 310px; max-width: 600px; height: 400px; margin: 0 auto"></div>

		<script type="text/javascript">

// Create the chart
Highcharts.chart('container', {
    chart: {
        type: 'pie'
    },
    title: {
        text: 'Browser market shares. January, 2015 to May, 2015'
    },
    subtitle: {
        text: 'Click the slices to view versions. Source: netmarketshare.com.'
    },
    plotOptions: {
        series: {
            dataLabels: {
                enabled: true,
                format: '{point.name}: {point.y:.1f}%'
            }
        }
    },

    tooltip: {
        headerFormat: '<span style="font-size:11px">{series.name}</span><br>',
        pointFormat: '<span style="color:{point.color}">{point.name}</span>: <b>{point.y:.2f}%</b> of total<br/>'
    },
    series: [{
        name: 'Brands',
        colorByPoint: true,
        data: [
        {% for c in expense_main_category %}
        {
            name: "{{ c.main_category__category_name }}",
            y: {{ c.check_sum }},
            drilldown: '{{ c.main_category__category_name }}'
        }{% if not forloop.last %},{% endif %}

        {% endfor %}
        ]
    }],
    drilldown: {
        series: [
        {% for c in expense_main_category %}

        {
            name: '{{ c.main_category__category_name }}',
            id: '{{ c.main_category__category_name }}',
            data: [
                {% for i in expense_main_sub_category %}
                    {% if c.main_category__category_name == i.main_category__category_name %}
                    ['{{ i.sub_category__category_name }}', {{i.check_sum}}] {% if not forloop.last %},{% endif %}
                    {% endif %}
                {% endfor %}
            ]
        }{% if not forloop.last %},{% endif %}
        {% endfor %}]
    }
});
		</script>
	</body>
</html>